/** Merge tokens supported in Google Doc / Word / PDF invoice templates. */

export const INVOICE_MERGE_FIELDS = [
  "invoice_number",
  "status",
  "issue_date",
  "due_date",
  "client_name",
  "client_email",
  "client_address",
  "candidate_name",
  "job_title",
  "fee_type",
  "fee_percent",
  "fee_flat",
  "salary_basis",
  "salary_range",
  "total",
  "subtotal",
  "currency",
  "notes",
  "payment_terms",
  "from_name",
  "from_address",
  "from_email",
  "from_phone",
  "description",
  "line_items",
] as const;
